name: pr_check

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create wheel
        run: |
          pip3 install setuptools
          python3 setup.py bdist_wheel --universal
          pip3 install dist/*.whl

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install flake8
        run: |
          pip3 install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        run: |
          pytest
