name: release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: remorses/bump-version@js
        with:
            version_file: ./client/VERSION
            github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
            version_file: ./client/VERSION
            github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: create wheel
        run: |
          python3 setup.py bdist_wheel --universal
          pip3 install dist/*.whl

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip3 install twine
          twine upload dist/*.whl