name: release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create wheel
        run: |
          python3 setup.py bdist_wheel --universal
          pip3 install dist/pong_game-0.0.0-py2.py3-none-any.whl

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip3 install twine
          twine upload dist/*.whl