name: release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v2
        with:
          path: pong_game

      - uses: RalfG/python-wheels-manylinux-build@v0.3.3
        with:
          python-versions: 'cp36-cp36m cp37-cp37m'
          package-path: 'pong_game'
          pip-wheel-args: '-w ./dist --no-deps'

      - name: Install python dependencies
        run: |
         python -m pip install --upgrade pip
         python -m pip install twine

    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload wheelhouse/*-manylinux*.whl